sonar.projectKey=jregeimbal_latent-space-dance-off
sonar.organization=jregeimbal
sonar.projectName=latent-space-dance-off
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.language=py
sonar.python.version=3.12
